name: qr_flutter
description: >
  QR.Flutter is a Flutter library for simple and fast QR code rendering via a
  Widget or custom painter.
version: 3.2.2
homepage: https://github.com/lukef/qr.flutter

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.7.0"

dependencies:
  flutter:
    sdk: flutter
  qr: ">=1.2.0 <=2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.4

flutter:
  uses-material-design: false
